apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bakery
  name: bakery-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bakery
  template:
    metadata:
      labels:
        app: bakery
      name: bakery
    spec:
      containers:
        - name: web
          image: stevenfollis/bakery:web
      # tolerations:
      #   - key: "os"
      #     operation: "equal"
      #     value: "windows"
      #     effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: windows
        # node.kubernetes.io/windows-build: "10.0.17763" # Use starting in K8S v1.17
---
apiVersion: v1
kind: Service
metadata:
  name: bakery-service
  labels:
    name: bakery-service
spec:
  ports:
    - port: 80
  selector:
    app: bakery
  # type: LoadBalancer
  type: NodePort
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"pacman","namespace":"launch"},"spec":{"gateways":["istio-system/demo-gateway"],"hosts":["pacman-nodejs.launch.kube.webinar.mirantis-demos.mirantis.com"],"http":[{"match":[{"uri":{"prefix":"/"}}],"route":[{"destination":{"host":"pacman","port":{"number":80}}}]}]}}
  generation: 1
  name: bakery
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/bakery/virtualservices/bakery
spec:
  gateways:
  - istio-system/demo-gateway
  hosts:
  - bakery.launch.kube.webinar.mirantis-demos.mirantis.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: bakery
        port:
          number: 80