apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bakery
  name: bakery-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bakery
  template:
    metadata:
      labels:
        app: bakery
      name: bakery
    spec:
      containers:
        - name: web
          image: dtr.webinar.mirantis-demos.mirantis.com/launch/bakery:2020.05.01
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: bakery-service
  labels:
    name: bakery-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: bakery
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bakery
spec:
  hosts:
    - bakery.launch.kube.webinar.mirantis-demos.mirantis.com
  gateways:
    - istio-system/demo-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: bakery-service
            port:
              number: 80

  